# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Shalom Pytest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '00 12 * * *'
  workflow_dispatch:
    inputs:
      suite:
        description: 'Test suite'
        required: true
        default: 'smoke'
        type: choice
        options:
          - smoke
          - regression
          - api
          - web

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-python@v6
      with:
        python-version: '3.9.25'
        cache: 'pip'
    - run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

  test_smoke:
    if: ${{ inputs.suite == 'smoke' || github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-python@v6
      with:
        python-version: '3.9.25'
        cache: 'pip'
    - run: pip install -r requirements.txt
    - name: Run smoke suite test
      run: |
        python -m pytest --report-log=logs/test_report.txt --html=logs/test_report.html --base_api_url=${{ vars.BASE_API_URL }} -m smoke tests/
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: artifacts
        path: |
          logs/
          *.png

  test_regression:
    if: ${{ inputs.suite == 'regression' || github.event_name == 'push' || github.event_name == 'schedule' }}
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-python@v6
      with:
        python-version: '3.9.25'
        cache: 'pip'
    - run: pip install -r requirements.txt
    - name: Run regression suite
      run: |
        python -m pytest --report-log=logs/test_report.txt --html=logs/test_report.html --base_api_url=${{ vars.BASE_API_URL }} tests/
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: artifacts
        path: |
          logs/
          *.png

  test_api:
    if: ${{ inputs.suite == 'api' }}
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-python@v6
      with:
        python-version: '3.9.25'
        cache: 'pip'
    - run: pip install -r requirements.txt
    - name: Run api related tests
      run: |
        python -m pytest --report-log=logs/test_report.txt --html=logs/test_report.html --base_api_url=${{ vars.BASE_API_URL }} -m ${{ inputs.suite }} tests/
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: artifacts
        path: |
          logs/
          *.png

  test_web:
    if: ${{ inputs.suite == 'web' }}
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-python@v6
      with:
        python-version: '3.9.25'
        cache: 'pip'
    - run: pip install -r requirements.txt
    - name: Run web related tests
      run: |
        python -m pytest --report-log=logs/test_report.txt --html=logs/test_report.html --base_api_url=${{ vars.BASE_API_URL }} -m ${{ inputs.suite }} tests/
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: artifacts
        path: |
          logs/
          *.png

  test_failure:
    needs: [test_smoke, test_regression, test_api, test_web]
    if: ${{ always() && contains(needs.*.result, 'failure') }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-python@v6
      with:
        python-version: '3.9.25'
        cache: 'pip'
    - run: pip install -r requirements.txt

    - uses: actions/download-artifact@v5
      with:
        name: artifacts
    - name: retrieve and re-run failed tests
      run: |
        failed_tests=`python3 get_failed_tests.py logs/test_report.html last_failures.json`
        echo $failed_tests
        python -m pytest --report-log=logs/test_report.txt --html=logs/test_report.html --base_api_url=${{ vars.BASE_API_URL }} tests/ -k "$failed_tests"
